# Generated by Django 4.2.25 on 2026-02-13 15:41

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_interactiveuser_code'),
        ('location', '0018_auto_20230925_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMunicipality',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='UserMunicipalityID', primary_key=True, serialize=False)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
                ('location', models.ForeignKey(db_column='LocationId', on_delete=django.db.models.deletion.DO_NOTHING, to='location.location')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='core.interactiveuser')),
            ],
            options={
                'db_table': 'tblUsersMunicipalities',
                'managed': True,
            },
        ),
    ]
